export const categories = [
  {
    id: 1,
    image: "/images/honey_round.png",
    title: "Honey",
    desc: "Pure and natural honey from local farms.",
    items: [
        {
          id: 1,
          name: "Organic Honey",
          price: "250/L",
          seller: "Ramesh Kumar",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXG1vAaZIzU7n4w7lEAFekb5Lv-BSE15g_RQ&s"
        },
        {
          id: 2,
          name: "Wildflower Honey",
          price: "300/L",
          seller: "Anjali Sharma",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxqBLOUXV_1LXTD8FfDQ3WceyoZg9bp865e6rWnig1gRePCCbm43kE9or5-2AnmwjIWsM&usqp=CAU"
        },
        {
          id: 3,
          name: "Acacia Honey",
          price: "350/L",
          seller: "Rajesh Gupta",
          img:"https://easthillhoney.com/cdn/shop/products/comb-1.jpg?v=1699844177&width=1445"
        },
        {
          id: 4,
          name: "Eucalyptus Honey",
          price: "400/L",
          seller: "Priya Mehta",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOvEhwDFKEY9DpIAwbimd7hLMcwZpZaGyRkA&s"
        },
        {
          id: 5,
          name: "Mustard Honey",
          price: "280/L",
          seller: "Suresh Singh",
          img:"https://img1.wsimg.com/isteam/ip/2b3b8aa4-e1f8-4bff-afbe-54199b484cf8/ols/Honey%20-%20MHF%20-%20Murder%20Hornet.jpg/:/rs=w:1200,h:1200"
        },
        {
          id: 6,
          name: "Clover Honey",
          price: "330/L",
          seller: "Neha Verma",
          img:"https://d2ki7eiqd260sq.cloudfront.net/honey37706fd8-f3d4-4f75-b111-fa6ac9134b21.jpg"
        },
        {
          id: 7,
          name: "Tulsi Honey",
          price: "350/L",
          seller: "Amit Tiwari",
          img:"https://m.media-amazon.com/images/I/610k-UsImNL._AC_UF1000,1000_QL80_.jpg"
        },
        {
          id: 8,
          name: "Multiflora Honey",
          price: "270/L",
          seller: "Pooja Patel",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXG1vAaZIzU7n4w7lEAFekb5Lv-BSE15g_RQ&s"
        },
        {
          id: 9,
          name: "Neem Honey",
          price: "310/L",
          seller: "Arjun Malhotra",
          img:"https://d2ki7eiqd260sq.cloudfront.net/honey37706fd8-f3d4-4f75-b111-fa6ac9134b21.jpg"
        },
        {
          id: 10,
          name: "Forest Honey",
          price: "380/L",
          seller: "Deepak Yadav",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXG1vAaZIzU7n4w7lEAFekb5Lv-BSE15g_RQ&s"
        },
        {
          id: 11,
          name: "Jamun Honey",
          price: "400/L",
          seller: "Sneha Chaturvedi",
          img:"https://m.media-amazon.com/images/I/610k-UsImNL._AC_UF1000,1000_QL80_.jpg"
        },
        {
          id: 12,
          name: "Sunflower Honey",
          price: "320/L",
          seller: "Vikram Sinha",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXG1vAaZIzU7n4w7lEAFekb5Lv-BSE15g_RQ&s"
        },
        {
          id: 13,
          name: "Lychee Honey",
          price: "350/L",
          seller: "Manisha Nair",
          img:"https://d2ki7eiqd260sq.cloudfront.net/honey37706fd8-f3d4-4f75-b111-fa6ac9134b21.jpg"
        },
        {
          id: 14,
          name: "Himalayan Honey",
          price: "500/L",
          seller: "Gaurav Rathi",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXG1vAaZIzU7n4w7lEAFekb5Lv-BSE15g_RQ&s"
        },
        {
          id: 15,
          name: "Almond Blossom Honey",
          price: "450/L",
          seller: "Preeti Sharma",
          img:"https://m.media-amazon.com/images/I/610k-UsImNL._AC_UF1000,1000_QL80_.jpg"
        },
      ]      
  },
  {
    id: 2,
    image: "/images/tea_round.png",
    title: "Tea",
    desc: "A variety of organic teas.",
    items: [
        {
          id: 1,
          name: "Darjeeling Tea",
          price: "400/kg",
          seller: "Rohit Chatterjee",
          img:"https://d11qgm9a5k858y.cloudfront.net/f02pgwi6e4eplu8bp7y3m21aiver"
        },
        {
          id: 2,
          name: "Assam Tea",
          price: "350/kg",
          seller: "Ananya Dutta",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7qJQJ4QaAiB1kP2SEaLXwtPtehoDVpAtWhw&s"
        },
        {
          id: 3,
          name: "Nilgiri Tea",
          price: "300/kg",
          seller: "Arvind Nair",
          img:"https://www.octavius.in/cdn/shop/products/CA4A5330-ExclusiveIndianMasala.jpg?v=1703331714"
        },
        {
          id: 4,
          name: "Green Tea",
          price: "450/kg",
          seller: "Simran Kapoor",
          img:"https://diy.penkraft.in/productImages/KA%20SQ%20Coaster.jpg"
        },
        {
          id: 5,
          name: "Masala Chai",
          price: "380/kg",
          seller: "Siddharth Jain",
          img:"https://i5.walmartimages.com/seo/Grove-Square-Chai-Latte-Tea-8-47-oz-Box_7b05f125-cd96-4eb9-8e1b-4c86baeeaa23.bac75636758e6adafe4b4ed87a9f2a1d.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
        },
        {
          id: 6,
          name: "White Tea",
          price: "600/kg",
          seller: "Ritika Sharma",
          img:"https://diy.penkraft.in/productImages/KA%20SQ%20Coaster.jpg"
        },
        {
          id: 7,
          name: "Herbal Tea",
          price: "500/kg",
          seller: "Aditya Thakur",
          img:"https://www.octavius.in/cdn/shop/products/CA4A5330-ExclusiveIndianMasala.jpg?v=1703331714"
        },
        {
          id: 8,
          name: "Oolong Tea",
          price: "550/kg",
          seller: "Nisha Mishra",
          img:"https://i5.walmartimages.com/seo/Grove-Square-Chai-Latte-Tea-8-47-oz-Box_7b05f125-cd96-4eb9-8e1b-4c86baeeaa23.bac75636758e6adafe4b4ed87a9f2a1d.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
        },
        {
          id: 9,
          name: "Chamomile Tea",
          price: "700/kg",
          seller: "Tarun Joshi",
          img:"https://diy.penkraft.in/productImages/KA%20SQ%20Coaster.jpg"
        },
        {
          id: 10,
          name: "Lemon Tea",
          price: "320/kg",
          seller: "Aarti Gupta",
          img:"https://www.octavius.in/cdn/shop/products/CA4A5330-ExclusiveIndianMasala.jpg?v=1703331714"
        },
        {
          id: 11,
          name: "Tulsi Tea",
          price: "400/kg",
          seller: "Karan Malhotra",
          img:"https://i5.walmartimages.com/seo/Grove-Square-Chai-Latte-Tea-8-47-oz-Box_7b05f125-cd96-4eb9-8e1b-4c86baeeaa23.bac75636758e6adafe4b4ed87a9f2a1d.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF"
        },
        {
          id: 12,
          name: "Mint Tea",
          price: "350/kg",
          seller: "Pallavi Singh",
          img:"https://i.pinimg.com/736x/0e/e5/91/0ee5917b2b2d385f40f6308615f4c7fa.jpg"
        },
        {
          id: 13,
          name: "Black Tea",
          price: "300/kg",
          seller: "Rajiv Khanna",
          img:"https://diy.penkraft.in/productImages/KA%20SQ%20Coaster.jpg"
        },
        {
          id: 14,
          name: "Organic Tea",
          price: "450/kg",
          seller: "Meera Iyer",
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj2OQTPeiFJS51l19_mCjBaNhR7dStYKVUrA&s"
        },
        {
          id: 15,
          name: "Kashmiri Kahwa",
          price: "600/kg",
          seller: "Faizan Ahmad",
          img:"https://i.pinimg.com/736x/0e/e5/91/0ee5917b2b2d385f40f6308615f4c7fa.jpg"
        },
      ]
      
  },
  {
    id: 3,
    image: "/images/cotton_round.png",
    title: "Cotton",
    desc: "Soft and durable cotton products.",
    items: [
        {
          id: 1,
          name: "Cotton Bedsheet",
          price: "800/unit",
          seller: "Aman Verma",
          img: "https://5.imimg.com/data5/NY/SD/MY-2650548/designer-cotton-bed-sheets-500x500.jpg",
        },
        {
          id: 2,
          name: "Cotton Towel",
          price: "400/unit",
          seller: "Neha Mishra",
          img: "https://cdn.shopify.com/s/files/1/0031/3156/0054/products/Hotel-Supima-Cotton-Towel-Set-White-Hero_2048x.jpg?v=1643974646",
        },
        {
          id: 3,
          name: "Cotton Kurta",
          price: "1200/unit",
          seller: "Ravi Sharma",
          img: "https://cdn.shopify.com/s/files/1/0406/1092/5905/products/Lightbluecottonkurta3.jpg?v=1629143205",
        },
        {
          id: 4,
          name: "Cotton Saree",
          price: "1500/unit",
          seller: "Priya Menon",
          img: "https://m.media-amazon.com/images/I/81cobXilGUL._UY741_.jpg",
        },
        {
          id: 5,
          name: "Cotton Handkerchief",
          price: "150/pack",
          seller: "Rahul Khanna",
          img: "https://5.imimg.com/data5/WG/FX/MY-21177852/cotton-handkerchief-500x500.jpg",
        },
        {
          id: 6,
          name: "Cotton Bags",
          price: "300/unit",
          seller: "Sneha Kapoor",
          img: "https://5.imimg.com/data5/ZZ/TC/MY-12613493/cotton-bag-500x500.jpg",
        },
        {
          id: 7,
          name: "Cotton Fabric",
          price: "250/meter",
          seller: "Ankit Gupta",
          img: "https://5.imimg.com/data5/QP/KP/MY-3434938/cotton-fabric-500x500.jpg",
        },
        {
          id: 8,
          name: "Cotton Pillow Cover",
          price: "500/pair",
          seller: "Shivani Desai",
          img: "https://5.imimg.com/data5/NY/PG/MY-2988930/pillow-covers-500x500.jpg",
        },
        {
          id: 9,
          name: "Cotton Curtains",
          price: "1200/pair",
          seller: "Karan Malhotra",
          img: "https://m.media-amazon.com/images/I/71DNjdE9nyL._SL1500_.jpg",
        },
        {
          id: 10,
          name: "Cotton Rugs",
          price: "900/unit",
          seller: "Manisha Rao",
          img: "https://5.imimg.com/data5/CC/VJ/MY-3775014/cotton-rugs-500x500.jpg",
        },
        {
          id: 11,
          name: "Cotton T-Shirts",
          price: "500/unit",
          seller: "Aakash Nair",
          img: "https://5.imimg.com/data5/CP/DA/HO/SELLER-13761849/mens-plain-cotton-t-shirts-500x500.jpg",
        },
        {
          id: 12,
          name: "Cotton Apron",
          price: "700/unit",
          seller: "Ritika Singh",
          img: "https://5.imimg.com/data5/NH/YS/MY-5309258/cotton-apron-500x500.jpg",
        },
        {
          id: 13,
          name: "Cotton Duvet Cover",
          price: "2000/unit",
          seller: "Vikram Kumar",
          img: "https://m.media-amazon.com/images/I/91VIApx5KwL._AC_UL1500_.jpg",
        },
        {
          id: 14,
          name: "Cotton Napkins",
          price: "300/pack",
          seller: "Pooja Agarwal",
          img: "https://5.imimg.com/data5/YH/GH/GLADMIN-15154278/dinner-napkin-500x500.jpg",
        },
        {
          id: 15,
          name: "Cotton Baby Blanket",
          price: "1500/unit",
          seller: "Suresh Joshi",
          img: "https://m.media-amazon.com/images/I/71yoH6CxR5L._SX522_.jpg",
        },
      ]
      
  },
  {
    id: 4,
    image: "/images/grain_round.png",
    title: "Grain",
    desc: "Fresh grains from local farmers.",
    items: [
        {
          id: 1,
          name: "Basmati Rice",
          price: "120/kg",
          seller: "Rajesh Kumar",
          img: "https://5.imimg.com/data5/QM/JH/YM/SELLER-2091581/basmati-rice-500x500.jpg",
        },
        {
          id: 2,
          name: "Wheat Flour",
          price: "40/kg",
          seller: "Sunita Patel",
          img: "https://m.media-amazon.com/images/I/71ptZmHaBvL._SX522_.jpg",
        },
        {
          id: 3,
          name: "Moong Dal",
          price: "90/kg",
          seller: "Anil Sharma",
          img: "https://m.media-amazon.com/images/I/41lmTFeGh2L.jpg",
        },
        {
          id: 4,
          name: "Chana Dal",
          price: "85/kg",
          seller: "Seema Verma",
          img: "https://5.imimg.com/data5/XE/MY/GLADMIN-624382/chana-dal-500x500.jpg",
        },
        {
          id: 5,
          name: "Masoor Dal",
          price: "100/kg",
          seller: "Arun Singh",
          img: "https://5.imimg.com/data5/UB/DP/MY-42228078/masoor-dal-500x500.jpg",
        },
        {
          id: 6,
          name: "Urad Dal",
          price: "110/kg",
          seller: "Neha Gupta",
          img: "https://5.imimg.com/data5/WU/OV/MY-42228078/urad-dal-500x500.jpg",
        },
        {
          id: 7,
          name: "Toor Dal",
          price: "95/kg",
          seller: "Prakash Jha",
          img: "https://5.imimg.com/data5/BW/OK/MY-42228078/toor-dal-500x500.jpg",
        },
        {
          id: 8,
          name: "Barley",
          price: "50/kg",
          seller: "Sanjay Rathore",
          img: "https://5.imimg.com/data5/SE/QM/MY-11577923/barley-500x500.jpg",
        },
        {
          id: 9,
          name: "Quinoa",
          price: "400/kg",
          seller: "Aditi Mishra",
          img: "https://5.imimg.com/data5/YB/EH/GLADMIN-2/quinoa-grain-500x500.jpg",
        },
        {
          id: 10,
          name: "Millet",
          price: "60/kg",
          seller: "Kiran Desai",
          img: "https://5.imimg.com/data5/KQ/SL/MY-2995335/millet-500x500.jpg",
        },
        {
          id: 11,
          name: "Corn",
          price: "30/kg",
          seller: "Nitin Chauhan",
          img: "https://5.imimg.com/data5/BP/NI/MY-16237887/corn-seeds-500x500.jpg",
        },
        {
          id: 12,
          name: "Oats",
          price: "300/kg",
          seller: "Sneha Kapoor",
          img: "https://5.imimg.com/data5/PI/RU/MY-16186556/whole-oats-500x500.jpg",
        },
        {
          id: 13,
          name: "Soybean",
          price: "75/kg",
          seller: "Vijay Shukla",
          img: "https://5.imimg.com/data5/YT/DX/GLADMIN-2/soyabean-500x500.jpg",
        },
        {
          id: 14,
          name: "Ragi",
          price: "80/kg",
          seller: "Ravi Reddy",
          img: "https://5.imimg.com/data5/WQ/NV/MY-17062434/ragi-500x500.jpg",
        },
        {
          id: 15,
          name: "Chia Seeds",
          price: "500/kg",
          seller: "Anjana Kulkarni",
          img: "https://5.imimg.com/data5/HA/KQ/MY-3211639/chia-seeds-500x500.jpg",
        },
      ]      
  },
  {
    id: 5,
    image: "/images/spices_round.png",
    title: "Spices",
    desc: "Organic spices for every dish.",
    items: [
        {
          id: 1,
          name: "Turmeric Powder",
          price: "200/kg",
          seller: "Ramesh Kumar",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/1/GX/CG/QU/22000020/turmeric-powder-500x500.jpg",
        },
        {
          id: 2,
          name: "Coriander Powder",
          price: "150/kg",
          seller: "Anjali Verma",
          img: "https://5.imimg.com/data5/HL/HW/MY-2/coriander-powder-500x500.jpg",
        },
        {
          id: 3,
          name: "Cumin Seeds",
          price: "300/kg",
          seller: "Vikram Sharma",
          img: "https://5.imimg.com/data5/PP/IM/MY-3337328/cumin-seeds-500x500.jpg",
        },
        {
          id: 4,
          name: "Red Chili Powder",
          price: "250/kg",
          seller: "Sneha Joshi",
          img: "https://5.imimg.com/data5/PI/RX/MY-26951526/red-chilli-powder-500x500.jpg",
        },
        {
          id: 5,
          name: "Black Pepper",
          price: "600/kg",
          seller: "Arjun Nair",
          img: "https://5.imimg.com/data5/XR/IK/GLADMIN-2/black-pepper-500x500.jpg",
        },
        {
          id: 6,
          name: "Cloves",
          price: "800/kg",
          seller: "Kavita Patel",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/3/OE/UE/SD/2309001/cloves-500x500.jpg",
        },
        {
          id: 7,
          name: "Cardamom",
          price: "1500/kg",
          seller: "Rajiv Kapoor",
          img: "https://5.imimg.com/data5/OY/HM/GLADMIN-2/cardamom-500x500.jpg",
        },
        {
          id: 8,
          name: "Fenugreek Seeds",
          price: "120/kg",
          seller: "Anita Das",
          img: "https://5.imimg.com/data5/HH/NE/MY-1040777/fenugreek-seeds-500x500.jpg",
        },
        {
          id: 9,
          name: "Mustard Seeds",
          price: "100/kg",
          seller: "Sandeep Mishra",
          img: "https://5.imimg.com/data5/VB/EY/MY-4010166/mustard-seeds-500x500.jpg",
        },
        {
          id: 10,
          name: "Cinnamon Sticks",
          price: "900/kg",
          seller: "Priya Thakur",
          img: "https://5.imimg.com/data5/XO/NG/MY-3006544/cinnamon-stick-500x500.jpg",
        },
        {
          id: 11,
          name: "Nutmeg",
          price: "1000/kg",
          seller: "Abhishek Sen",
          img: "https://5.imimg.com/data5/GV/HO/GLADMIN-2/nutmeg-500x500.jpg",
        },
        {
          id: 12,
          name: "Bay Leaves",
          price: "200/kg",
          seller: "Aditi Rao",
          img: "https://5.imimg.com/data5/VP/FD/MY-55265726/bay-leaf-500x500.jpg",
        },
        {
          id: 13,
          name: "Star Anise",
          price: "1200/kg",
          seller: "Pooja Gupta",
          img: "https://5.imimg.com/data5/YT/IX/MY-2407397/star-anise-500x500.jpg",
        },
        {
          id: 14,
          name: "Asafoetida",
          price: "3000/kg",
          seller: "Deepak Agarwal",
          img: "https://5.imimg.com/data5/VV/II/GLADMIN-2/asafoetida-500x500.jpg",
        },
        {
          id: 15,
          name: "Fennel Seeds",
          price: "200/kg",
          seller: "Nisha Yadav",
          img: "https://5.imimg.com/data5/BF/JP/MY-2963832/fennel-seeds-500x500.jpg",
        },
      ]
      
  },
  {
    id: 6,
    image: "/images/wood_round.png",
    title: "Wood",
    desc: "Quality wood products for construction.",
    items: [
        {
          id: 1,
          name: "Teak Wood Plank",
          price: "3500/cubic ft",
          seller: "Ramesh Singh",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/5/RG/XI/QL/21001264/teak-wood-plank-500x500.jpg",
        },
        {
          id: 2,
          name: "Rosewood Logs",
          price: "4500/cubic ft",
          seller: "Anita Sharma",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/8/YN/SI/RO/6201186/rosewood-log-500x500.jpg",
        },
        {
          id: 3,
          name: "Sandalwood Blocks",
          price: "15000/kg",
          seller: "Rajiv Malhotra",
          img: "https://5.imimg.com/data5/XN/AD/MY-10598269/sandalwood-block-500x500.jpg",
        },
        {
          id: 4,
          name: "Pinewood Sheets",
          price: "2500/cubic ft",
          seller: "Vikram Gupta",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/5/UZ/EG/WE/21062356/pinewood-sheets-500x500.jpg",
        },
        {
          id: 5,
          name: "Mahogany Wood",
          price: "5000/cubic ft",
          seller: "Sneha Jain",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/3/SN/AM/VB/1303586/mahogany-wood-500x500.jpg",
        },
        {
          id: 6,
          name: "Oak Timber",
          price: "4000/cubic ft",
          seller: "Sandeep Yadav",
          img: "https://5.imimg.com/data5/LX/SB/MY-22910755/oak-wood-timber-500x500.jpg",
        },
        {
          id: 7,
          name: "Mango Wood",
          price: "3000/cubic ft",
          seller: "Deepa Kulkarni",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/8/FH/QT/SH/23837213/mango-wood-500x500.jpg",
        },
        {
          id: 8,
          name: "Bamboo Wood",
          price: "2000/cubic ft",
          seller: "Arjun Menon",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/1/KH/RZ/QJ/780203/bamboo-wood-500x500.jpg",
        },
        {
          id: 9,
          name: "Walnut Wood",
          price: "6000/cubic ft",
          seller: "Pooja Verma",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/6/VB/JI/MO/80007082/walnut-wood-500x500.jpg",
        },
        {
          id: 10,
          name: "Sheesham Wood",
          price: "3500/cubic ft",
          seller: "Manish Thakur",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/7/ON/LR/CE/20570427/sheesham-wood-500x500.jpg",
        },
        {
          id: 11,
          name: "Birch Plywood",
          price: "2000/cubic ft",
          seller: "Kavita Nair",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/3/AD/NQ/AF/116869/birch-plywood-500x500.jpg",
        },
        {
          id: 12,
          name: "Deodar Wood",
          price: "3000/cubic ft",
          seller: "Tarun Bhardwaj",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/12/XK/AI/QX/174707/deodar-wood-500x500.jpg",
        },
        {
          id: 13,
          name: "Maple Wood",
          price: "5500/cubic ft",
          seller: "Rekha Das",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/12/BA/UX/MJ/22279029/maple-wood-500x500.jpg",
        },
        {
          id: 14,
          name: "Hardwood Logs",
          price: "4500/cubic ft",
          seller: "Ajay Mehta",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/10/FP/XF/SW/2308388/hardwood-logs-500x500.jpg",
        },
        {
          id: 15,
          name: "Teakwood Veneer",
          price: "5000/cubic ft",
          seller: "Aarti Kapoor",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/8/RT/ZJ/TU/14130214/teakwood-veneer-500x500.jpg",
        },
      ]      
  },
  {
    id: 7,
    image: "/images/med_round.png",
    title: "Medicine",
    desc: "Traditional and herbal medicines.",
    items: [
        {
          id: 1,
          name: "Ayurvedic Pain Relief Oil",
          price: "200/bottle",
          seller: "Dr. Ramesh Bhat",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/8/AX/CE/MD/16878629/pain-relief-oil-500x500.jpg",
        },
        {
          id: 2,
          name: "Herbal Cough Syrup",
          price: "150/bottle",
          seller: "Dr. Anjali Mehta",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/3/BD/ML/LF/4448939/herbal-cough-syrup-500x500.jpg",
        },
        {
          id: 3,
          name: "Digestive Tablets",
          price: "100/pack",
          seller: "Dr. Arvind Joshi",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/8/LT/NM/FT/1264316/digestive-tablets-500x500.jpg",
        },
        {
          id: 4,
          name: "Herbal Immunity Booster",
          price: "250/bottle",
          seller: "Dr. Kavita Sharma",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/7/RE/YC/RU/765280/immunity-booster-500x500.jpg",
        },
        {
          id: 5,
          name: "Aloe Vera Gel",
          price: "300/bottle",
          seller: "Dr. Manish Jain",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/3/UN/TG/JL/5766375/aloe-vera-gel-500x500.jpg",
        },
        {
          id: 6,
          name: "Neem Capsules",
          price: "200/pack",
          seller: "Dr. Pooja Verma",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/11/MK/IN/WD/23813720/neem-capsules-500x500.jpg",
        },
        {
          id: 7,
          name: "Chyawanprash",
          price: "500/bottle",
          seller: "Dr. Suresh Gupta",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/9/TS/WQ/VL/3790090/chyawanprash-500x500.jpg",
        },
        {
          id: 8,
          name: "Herbal Joint Pain Cream",
          price: "250/tube",
          seller: "Dr. Neha Kapoor",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/1/BD/FA/SA/192343/joint-pain-relief-cream-500x500.jpg",
        },
        {
          id: 9,
          name: "Turmeric Capsules",
          price: "300/pack",
          seller: "Dr. Aditya Thakur",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/6/QE/LR/SJ/8507404/turmeric-capsules-500x500.jpg",
        },
        {
          id: 10,
          name: "Ashwagandha Tablets",
          price: "350/pack",
          seller: "Dr. Swati Menon",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/5/AA/PH/EU/4523287/ashwagandha-tablets-500x500.jpg",
        },
        {
          id: 11,
          name: "Herbal Skin Care Cream",
          price: "400/tube",
          seller: "Dr. Vikram Rao",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/6/LP/TM/QG/746392/herbal-skin-care-cream-500x500.jpg",
        },
        {
          id: 12,
          name: "Tulsi Drops",
          price: "120/bottle",
          seller: "Dr. Alka Singh",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/5/AD/AN/GR/3846891/tulsi-drops-500x500.jpg",
        },
        {
          id: 13,
          name: "Herbal Hair Oil",
          price: "250/bottle",
          seller: "Dr. Rajesh Nair",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/9/SZ/IC/LK/3240567/herbal-hair-oil-500x500.jpg",
        },
        {
          id: 14,
          name: "Shilajit Resin",
          price: "1000/bottle",
          seller: "Dr. Faizan Ahmad",
          img: "https://5.imimg.com/data5/SELLER/Default/2021/12/ND/MK/GX/13503068/shilajit-resin-500x500.jpg",
        },
        {
          id: 15,
          name: "Herbal Eye Drops",
          price: "150/bottle",
          seller: "Dr. Arjun Khanna",
          img: "https://5.imimg.com/data5/SELLER/Default/2022/5/OU/NB/QX/5270848/herbal-eye-drops-500x500.jpg",
        },
      ]      
  },
  {
    id: 8,
    image: "/images/veg_round.png",
    title: "Vegetables",
    desc: "Fresh organic vegetables.",
    items: [
        {
          id: 1,
          name: "Organic Potatoes",
          price: "30/kg",
          seller: "Sandeep Kumar",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/05/Potato.jpg",
        },
        {
          id: 2,
          name: "Fresh Tomatoes",
          price: "40/kg",
          seller: "Anita Sharma",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Tomato.jpg",
        },
        {
          id: 3,
          name: "Spinach",
          price: "25/kg",
          seller: "Rajesh Patel",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Spinach.jpg",
        },
        {
          id: 4,
          name: "Cauliflower",
          price: "50/kg",
          seller: "Madhuri Joshi",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Cauliflower.jpg",
        },
        {
          id: 5,
          name: "Cabbage",
          price: "30/kg",
          seller: "Suresh Reddy",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Cabbage.jpg",
        },
        {
          id: 6,
          name: "Carrots",
          price: "40/kg",
          seller: "Geeta Iyer",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Carrot.jpg",
        },
        {
          id: 7,
          name: "Beans",
          price: "60/kg",
          seller: "Krishna Rao",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/05/Beans.jpg",
        },
        {
          id: 8,
          name: "Brinjal (Eggplant)",
          price: "35/kg",
          seller: "Nisha Verma",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Brinjal.jpg",
        },
        {
          id: 9,
          name: "Okra (Ladyfinger)",
          price: "45/kg",
          seller: "Vikram Singh",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Okra.jpg",
        },
        {
          id: 10,
          name: "Onions",
          price: "20/kg",
          seller: "Kavita Sharma",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Onion.jpg",
        },
        {
          id: 11,
          name: "Garlic",
          price: "80/kg",
          seller: "Ramesh Bhat",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Garlic.jpg",
        },
        {
          id: 12,
          name: "Green Chillies",
          price: "40/kg",
          seller: "Aarti Gupta",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/05/Green-Chillies.jpg",
        },
        {
          id: 13,
          name: "Cucumber",
          price: "25/kg",
          seller: "Harish Kumar",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Cucumber.jpg",
        },
        {
          id: 14,
          name: "Pumpkin",
          price: "35/kg",
          seller: "Vijay Rathi",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Pumpkin.jpg",
        },
        {
          id: 15,
          name: "Radish",
          price: "30/kg",
          seller: "Sunita Yadav",
          img: "https://www.organicfacts.net/wp-content/uploads/2020/04/Radish.jpg",
        },
      ]      
  },
  {
    id: 9,
    image: "/images/bee_round.png",
    title: "Bee Wax",
    desc: "Natural bee wax for various uses.",
    items: [
        {
          id: 1,
          name: "Organic Raw Beeswax",
          price: "800/kg",
          seller: "Amit Verma",
          img: "https://www.thebeeskneeswax.com/wp-content/uploads/2020/07/raw-beeswax.jpg",
        },
        {
          id: 2,
          name: "Pure Beeswax Pellets",
          price: "1000/kg",
          seller: "Sunita Patel",
          img: "https://www.beeswaxco.com/wp-content/uploads/2019/08/beeswax-pellets.jpg",
        },
        {
          id: 3,
          name: "Beeswax Candle Blocks",
          price: "1200/kg",
          seller: "Rahul Singh",
          img: "https://i.ebayimg.com/images/g/0akAAOSw2GlhBGdj/s-l1600.jpg",
        },
        {
          id: 4,
          name: "Beeswax Sheets for Candle Making",
          price: "1500/kg",
          seller: "Anjali Yadav",
          img: "https://www.wholesalebeeswaxcandles.com/wp-content/uploads/2020/07/Beeswax-Sheets.jpg",
        },
        {
          id: 5,
          name: "Beeswax Salve",
          price: "600/100g",
          seller: "Vikram Kumar",
          img: "https://cdn.shopify.com/s/files/1/0005/3173/3863/products/BeeswaxSalve_1000x.jpg?v=1598570932",
        },
        {
          id: 6,
          name: "Beeswax for Cosmetics",
          price: "900/kg",
          seller: "Ritika Gupta",
          img: "https://cdn.shopify.com/s/files/1/1614/4285/products/Pure-Beeswax-200-grams-front-3_720x.jpg?v=1620748967",
        },
        {
          id: 7,
          name: "Beeswax for Leather Conditioning",
          price: "700/kg",
          seller: "Harish Bhatt",
          img: "https://m.media-amazon.com/images/I/51qgXXunm4L._AC_SY300_.jpg",
        },
        {
          id: 8,
          name: "Beeswax Lip Balm",
          price: "500/100g",
          seller: "Kavita Mehta",
          img: "https://cdn.shopify.com/s/files/1/1006/0172/products/Beeswax_Lip_Balm_750x750.jpg?v=1613178037",
        },
        {
          id: 9,
          name: "Yellow Beeswax Blocks",
          price: "850/kg",
          seller: "Rohit Sharma",
          img: "https://www.ecobee.com/wp-content/uploads/2019/05/yellow-beeswax-blocks.jpg",
        },
        {
          id: 10,
          name: "Beeswax for Soap Making",
          price: "1100/kg",
          seller: "Nisha Verma",
          img: "https://www.lotioncrafter.com/assets/images/pure-beeswax.jpg",
        },
        {
          id: 11,
          name: "Beeswax Honeycomb Sheets",
          price: "1300/kg",
          seller: "Rajesh Kapoor",
          img: "https://i.ebayimg.com/images/g/ptAAAOSwONtZWyym/s-l1600.jpg",
        },
        {
          id: 12,
          name: "Beeswax Blocks for Candles",
          price: "1200/kg",
          seller: "Priya Joshi",
          img: "https://cdn.shopify.com/s/files/1/0132/4152/7085/products/raw-beeswax-blocks_360x.jpg?v=1607436467",
        },
        {
          id: 13,
          name: "Beeswax Wraps",
          price: "700/pack",
          seller: "Anita Desai",
          img: "https://images.unsplash.com/photo-1602421442907-8f758f6aab18",
        },
        {
          id: 14,
          name: "Refined Beeswax",
          price: "1000/kg",
          seller: "Amit Bansal",
          img: "https://cdn.beehivebotanicals.com/media/wysiwyg/Beeswax.jpg",
        },
        {
          id: 15,
          name: "Beeswax Polish",
          price: "500/200g",
          seller: "Tarun Yadav",
          img: "https://cdn.shopify.com/s/files/1/0093/6492/0785/products/Beeswax-Polish-1.jpg?v=1597070761",
        },
      ]      
  },
  {
    id: 10,
    image: "/images/bamboo_round.png",
    title: "Bamboo",
    desc: "Sustainable bamboo products.",
    items: [
        {
          id: 1,
          name: "Bamboo Toothbrush",
          price: "150/pc",
          seller: "Rohit Sharma",
          img: "https://i.ebayimg.com/images/g/xWIAAOSwN1ZfoJdL/s-l1600.jpg",
        },
        {
          id: 2,
          name: "Bamboo Cutting Board",
          price: "500/pc",
          seller: "Priya Gupta",
          img: "https://www.kitchenkingdom.com/wp-content/uploads/2020/05/Bamboo-Cutting-Board.jpg",
        },
        {
          id: 3,
          name: "Bamboo Tissues",
          price: "250/pack",
          seller: "Manish Patil",
          img: "https://www.bambooearthstore.com/wp-content/uploads/2020/10/bamboo-tissues.jpg",
        },
        {
          id: 4,
          name: "Bamboo Straw Set",
          price: "300/set",
          seller: "Nisha Kumari",
          img: "https://images-na.ssl-images-amazon.com/images/I/71Xz9OVl8QL._AC_SY679_.jpg",
        },
        {
          id: 5,
          name: "Bamboo Furniture",
          price: "2500/pc",
          seller: "Anil Kumar",
          img: "https://www.bambooliving.com/wp-content/uploads/2020/07/bamboo-furniture.jpg",
        },
        {
          id: 6,
          name: "Bamboo Charcoal",
          price: "350/kg",
          seller: "Kavita Mehta",
          img: "https://cdn.shopify.com/s/files/1/0220/4933/1742/products/bamboo_charcoal.jpg?v=1602616143",
        },
        {
          id: 7,
          name: "Bamboo Commode Chair",
          price: "1500/pc",
          seller: "Suresh Yadav",
          img: "https://5.imimg.com/data5/VK/NG/MY-6953009/bamboo-commode-chair-500x500.jpg",
        },
        {
          id: 8,
          name: "Bamboo Yoga Mat",
          price: "1200/pc",
          seller: "Aarti Verma",
          img: "https://www.indianbamboo.co.uk/wp-content/uploads/2020/09/Bamboo-Yoga-Mat.jpg",
        },
        {
          id: 9,
          name: "Bamboo Watch",
          price: "1000/pc",
          seller: "Harish Mehra",
          img: "https://cdn.shopify.com/s/files/1/0295/7172/7111/products/bamboo-watch-1.jpg?v=1607448201",
        },
        {
          id: 10,
          name: "Bamboo Bedding Set",
          price: "3000/set",
          seller: "Neha Jain",
          img: "https://cdn.shopify.com/s/files/1/0376/4846/8291/products/Bamboo-Bedding.jpg?v=1608185956",
        },
        {
          id: 11,
          name: "Bamboo Floor Mats",
          price: "800/m²",
          seller: "Rajesh Verma",
          img: "https://www.madeinbamboo.com/media/wysiwyg/Bamboo_Floor_Mats.jpg",
        },
        {
          id: 12,
          name: "Bamboo Paper",
          price: "500/pack",
          seller: "Amit Patel",
          img: "https://cdn.shopify.com/s/files/1/0140/3572/5699/products/Bamboo-Paper.jpg?v=1597051458",
        },
        {
          id: 13,
          name: "Bamboo Sunglasses",
          price: "1200/pc",
          seller: "Siddharth Reddy",
          img: "https://cdn.shopify.com/s/files/1/0147/2252/5952/products/bamboo-sunglasses.jpg?v=1607439824",
        },
        {
          id: 14,
          name: "Bamboo Floor Lamp",
          price: "1800/pc",
          seller: "Madhuri Deshmukh",
          img: "https://cdn.shopify.com/s/files/1/0462/7819/2509/products/Bamboo-Lamp.jpg?v=1606901324",
        },
        {
          id: 15,
          name: "Bamboo Chopsticks",
          price: "200/set",
          seller: "Vikram Singh",
          img: "https://www.bambooworld.com/wp-content/uploads/2020/09/bamboo-chopsticks.jpg",
        },
      ]      
  },
];
